

define({
	template: 'mustache',
	errorNotify: true,
	errorLog: false,
	mainContainer: '#mainContainer',
	page404: "modules/pages/views/404.html",
	firstPage: '/static/home.html',
	api: "t2api",
	
	staticPages: {
		about: '/static/about.html',

		partners: '/static/partners.html',
		tour: '/static/tour.html',
		resources: '/static/resources.html',
		
		people: {
			url: '/static/people.html',
			data: [
				{id:1, 
					name: 'Gon\347alves', 
					surname: 'Pedro', 
					image: '../scripts/modules/pages/img/people/pedro.pereira.jpg', 
					focus1: 'CTO',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:2, 
					name: 'Brito', 
					surname: 'Fabrice', 
					image: '../scripts/modules/pages/img/people/fabrice.brito.jpg', 
					focus1: 'CEO',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:3, 
					name: 'Maiozzi', 
					surname: 'Francesca', 
					image: '../scripts/modules/pages/img/people/francesca.maiozzi.jpg', 
					focus1: 'Corporate Administration',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:4, 
					name: 'Loeschau', 
					surname: 'Frank', 
					image: '../scripts/modules/pages/img/people/frank.loeschau.jpg', 
					focus1: 'Software Engineering',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:5, 
					name: 'D\'Andria',
					surname: 'Fabio', 
					image: '../scripts/modules/pages/img/people/fabio.dandria.jpg', 
					focus1: 'Operations Support',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:6, 
					name: 'Barchetta', 
					surname: 'Francesco', 
					image: '../scripts/modules/pages/img/people/francesco.barchetta.jpg', 
					focus1: 'Operations Support',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:7,
					name: 'Mathot', 
					surname: 'Emmanuel', 
					image: '../scripts/modules/pages/img/people/emmanuel.mathot.jpg', 
					focus1: 'Engineering Manager',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:8, 
					name: 'Caumont', 
					surname: 'Herv\351', 
					image: '../scripts/modules/pages/img/people/herve.caumont.jpg', 
					focus1: 'Operations Manager',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:9, 
					name: 'Boissier', 
					surname: 'Enguerran', 
					image: '../scripts/modules/pages/img/people/enguerran.boissier.jpg', 
					focus1: 'Software Engineering',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:10, 
					name: 'Rossi', 
					surname: 'Cesare', 
					image: '../scripts/modules/pages/img/people/cesare.rossi.jpg', 
					focus1: 'Operations Support',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:11, 
					name: 'Cerasuolo', 
					surname: 'Francesco', 
					image: '../scripts/modules/pages/img/people/francesco.cerasuolo.jpg', 
					focus1: 'Software Engineering',
					focus2: '',
					focus3: '',
					focus4: ''},
				{id:12, 
					name: 'D\'Andelis', 
					surname: 'Costanzo', 
					image: '../scripts/modules/pages/img/people/costanzo.dangelis.jpg', 
					focus1: 'Software Engineering',
					focus2: '',
					focus3: '',
					focus4: ''},
			],
			fnLoad: function(){
				// eventual javascript stuff
			}
		}

		

	},
	
});