define({
	list:[
		{id:1, 
			surname: 'Pedro', 
			name: 'Pereira Gon\347alves', 
			image: '/styles/img/people/pedro.pereira.jpg', 
			focus1: {title: 'Founder, CTO', url: 'http://en.wikipedia.org/wiki/Chief_technology_officer'},
			focus2: {title: 'Earth Observation', url: 'http://www.linkedin.com/skills/skill/Earth_Observation'},
			focus3: {title: 'Standards Editor', url: 'http://www.opengeospatial.org/standards/opensearchgeo'},
			focus4: {title: 'Business Strategy', url: 'http://dilbert.com/strips/comic/2009-09-09'},
			profile: 'Pedro is an Environmental Engineer with a PhD in Environmental Systems Analysis from the Faculdade de Ciencias e Tecnologia (Universidade Nova de Lisboa) and was a post-doctoral fellow at the European Space Agency.',
			linkedin: 'http://www.linkedin.com/in/p3dr0',
			twitter: 'https://twitter.com/gp3dr0'},
		{id:2, 
			surname: 'Fabrice', 
			name: 'Brito', 
			image: '/styles/img/people/fabrice.brito.jpg', 
			focus1: {title: 'Founder, CEO', url: 'https://en.wikipedia.org/wiki/Chief_executive_officer'},
			focus2: {title: 'Earth Observation', url: 'http://www.linkedin.com/skills/skill/Earth_Observation'},
			focus3: {title: 'Data Analytics', url: 'http://en.wikipedia.org/wiki/Data_analysis'},
			focus4: {title: 'Contracts', url: 'http://dilbert.com/strips/comic/2004-07-16'},
			profile: 'Fabrice has a Forest Engineering degree from the Instituto Superior de Agronomia (Universidade Tecnica de Lisboa) and was a researcher at the Instituto Geográfico Português and at the European Space Agency.',
			linkedin: 'http://it.linkedin.com/in/fabricebrito',
			twitter: 'https://twitter.com/FabriceBrito'},
		{id:3, 
			surname: 'Francesca', 
			name: 'Maiozzi', 
			image: '/styles/img/people/francesca.maiozzi.jpg', 
			focus1: {title: 'Corporate Administration', url: 'http://www.linkedin.com/skills/skill/Office_Administration'},					
			focus2: {title: 'Project Accounting', url: 'http://www.linkedin.com/skills/skill/Project_Accounting'},
			focus3: {title: 'Bookkeeping', url: 'http://en.wikipedia.org/wiki/Bookkeeping'},
			focus4: {title: 'Budgeting', url: 'http://dilbert.com/strips/comic/2006-03-09'},
			profile: '',
			linkedin: '',
			twitter: ''},
		{id:4, 
			surname: 'Frank', 
			name: 'Loeschau', 
			image: '/styles/img/people/frank.loeschau.jpg', 
			focus1: {title: 'Software Engineering', url: 'http://www.linkedin.com/skills/skill/Software_Engineering'},
			focus2: {title: 'Database Applications', url: 'http://en.wikipedia.org/wiki/Database_application'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Computer Science', url: 'http://en.wikipedia.org/wiki/Computer_science'},
			profile: 'Frank Loeschau has a Business Administration and Computer Science degree from the Dresden University of Technology.  Before joining Terradue he was a business analyst at the European Space Agency.',
			linkedin: 'http://www.linkedin.com/in/frankloeschau',
			twitter: 'https://twitter.com/AhoFrank'},
		{id:5, 
			surname: 'Francesco', 
			name: 'Barchetta', 
			image: '/styles/img/people/francesco.barchetta.jpg', 
			focus1: {title: 'Platform Operations', url: 'http://www.linkedin.com/skills/skill/Applications_Support'},
			focus2: {title: 'Software Engineering', url: 'http://en.wikipedia.org/wiki/Software_engineering'},
			focus3: {title: 'Data Processing', url: 'http://en.wikipedia.org/wiki/Data_Processing'},
			focus4: {title: 'Virtual Appliances', url: 'http://en.wikipedia.org/wiki/Virtual_appliance'},
			profile: '',					
			linkedin: 'http://www.linkedin.com/in/francescobarchetta',
			twitter: 'https://twitter.com/BarchettaFrance'},
		{id:6,
			surname: 'Emmanuel', 
			name: 'Mathot', 
			image: '/styles/img/people/emmanuel.mathot.jpg', 
			focus1: {title: 'Manager, Engineering', url: 'http://www.linkedin.com/skills/skill/Software_engineering'},
			focus2: {title: 'Continuous Delivery', url: 'http://en.wikipedia.org/wiki/Continuous_delivery'},
			focus3: {title: 'Product Engineering', url: 'http://en.wikipedia.org/wiki/Product_engineering'},
			focus4: {title: 'Process Optimization', url: 'http://geek-and-poke.com/geekandpoke/2009/3/23/let-the-clouds-make-your-life-easier.html'},
			profile: '',
			linkedin: 'http://it.linkedin.com/in/emmanuelmathot',
			twitter: 'https://twitter.com/emmanuelmathot'},
		{id:7, 
			surname: 'Herv\351', 
			name: 'Caumont', 
			image: '/styles/img/people/herve.caumont.jpg', 
			focus1: {title: 'Manager, Cloud Platform', url: 'http://www.linkedin.com/skills/skill/Cloud_Platform'},
			focus2: {title: 'Channel Strategy', url: 'http://www.linkedin.com/skills/skill/Channel_Strategy'},
			focus3: {title: 'Product Marketing', url: 'http://dilbert.com/strip/2015-01-21'},
			focus4: {title: 'Partner Programs', url: 'http://www.linkedin.com/skills/skill/Partner_Programs'},
			profile: '',
			linkedin: 'http://www.linkedin.com/in/hervecaumont',
			twitter: 'http://www.twitter.com/HerveCaumont'},
		{id:8, 
			surname: 'Enguerran', 
			name: 'Boissier', 
			image: '/styles/img/people/enguerran.boissier.jpg', 
			focus1: {title: 'Software Engineering', url: 'http://en.wikipedia.org/wiki/Software_engineering'},
			focus2: {title: 'Web Applications', url: 'http://en.wikipedia.org/wiki/Web_application'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Virtual Appliances', url: 'http://en.wikipedia.org/wiki/Virtual_appliance'},
			profile: '',
			linkedin: 'http://uk.linkedin.com/in/enguerranboissier',
			twitter: 'https://twitter.com/3ngu3'},
		{id:9, 
			surname: 'Cesare', 
			name: 'Rossi', 
			image: '/styles/img/people/cesare.rossi.jpg', 
			focus1: {title: 'Platform Operations', url: 'http://www.linkedin.com/skills/skill/IT_Operations'},
			focus2: {title: 'Distributed Computing', url: 'http://www.linkedin.com/skills/skill/Distributed_Systems'},
			focus3: {title: 'Cloud Orchestration', url: 'http://en.wikipedia.org/wiki/Orchestration_(computers)'},
			focus4: {title: 'Virtualization', url: 'http://en.wikipedia.org/wiki/Virtualization'},
			profile: '',
			linkedin: 'http://www.linkedin.com/in/rossicesare',
			twitter: 'https://twitter.com/Cesare_Ro'},
		{id:10, 
			surname: 'Francesco', 
			name: 'Cerasuolo', 
			image: '/styles/img/people/francesco.cerasuolo.jpg', 
			focus1: {title: 'Software Engineering', url: 'http://en.wikipedia.org/wiki/Software_engineering'},
			focus2: {title: 'Web Applications', url: 'http://en.wikipedia.org/wiki/Web_application'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Computer Science', url: 'http://en.wikipedia.org/wiki/Computer_science'},
			profile: '',
			linkedin: 'http://www.linkedin.com/pub/francesco-cerasuolo',
			twitter: 'https://twitter.com/CiccioCeras'},
		{id:11, 
			surname: 'Fabrizio', 
			name: 'Pacini', 
			image: '/styles/img/people/fabrizio.pacini.jpg', 
			focus1: {title: 'Manager, Key accounts', url: 'http://www.linkedin.com/skills/skill/key_account_manager'},
			focus2: {title: 'Distributed Computing', url: 'http://www.linkedin.com/skills/skill/Distributed_Systems'},
			focus3: {title: 'Systems Engineering', url: 'https://en.wikipedia.org/wiki/Systems_engineering'},
			focus4: {title: 'Data Processing', url: 'http://en.wikipedia.org/wiki/Data_Processing'},
			profile: '',
			linkedin: 'https://it.linkedin.com/in/fabrizio-pacini-567b0b'},
		{id:12, 
			surname: 'Manuela', 
			name: 'Sagona',
			image: '/styles/img/people/manuela.sagona.jpg', 
			focus1: {title: 'Platform Operations', url: 'http://www.linkedin.com/skills/skill/IT_Operations'},
			focus2: {title: 'Data Pipeline', url: 'https://www.linkedin.com/topic/data-pipeline'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Monitoring', url: 'http://geek-and-poke.com/geekandpoke/2011/8/22/hudsonjenkins-status-monitor.html'},
			profile: '',
			linkedin: '',
			twitter: ''},
		{id:13, 
			surname: 'Roberto', 
			name: 'Di Rienzo',
			image: '/styles/img/people/roberto.dirienzo.jpg', 
			focus1: {title: 'Software Engineering', url: 'http://www.linkedin.com/skills/skill/IT_Operations'},
			focus2: {title: 'Distributed Computing', url: 'http://www.linkedin.com/skills/skill/Distributed_Systems'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Computer Science', url: 'http://en.wikipedia.org/wiki/Computer_science'},
			profile: '',
			linkedin: '',
			twitter: ''},	
		{id:14, 
			surname: 'Blasco', 
			name: 'Brauzzi',
			image: '/styles/img/people/blasco.brauzzi.jpg', 
			focus1: {title: 'Software Engineering', url: 'http://www.linkedin.com/skills/skill/IT_Operations'},
			focus2: {title: 'Distributed Computing', url: 'http://www.linkedin.com/skills/skill/Distributed_Systems'},
			focus3: {title: 'Web Services API', url: 'http://www.linkedin.com/skills/skill/Web_Services_API'},
			focus4: {title: 'Computer Science', url: 'http://en.wikipedia.org/wiki/Computer_science'},
			profile: '',
			linkedin: 'https://www.linkedin.com/in/blascobrauzzi',
			twitter: ''},	
		]
});
