

require.config({
	baseUrl: '/scripts', 
	paths: {
		jquery: 'libs/jquery/jquery-1.10.2',
		jqueryUI: 'libs/jquery-ui/jquery-ui-1.10.3.custom.min',
		jqueryFullscreen: 'libs/jquery.fullscreen/js/jquery.fullscreen-0.3.5.min',
		jqueryValidate: 'libs/jquery.validate/js/jquery.validate',
		jqueryNamespace: 'libs/jquery.namespace/js/jqueryNamespace',
		jqrange: 'libs/jqrange/js/jQAllRangeSliders-min',
		can: 'libs/canjs/can.jquery',
		underscore: 'libs/underscore/underscore-min',
		bootstrap: 'libs/bootstrap/bootstrap.min',
		bootbox: 'libs/bootbox/bootbox.min',
		loadmask: 'libs/jquery.loadmask/jquery.loadmask.min',
		jsonTable: 'libs/jquery.jsonTable/js/jsonTable',
		jsonViewer: 'libs/jquery.jsonViewer/js/jquery.jsonViewer',
		datePicker: 'libs/datePicker/js/bootstrap-datepicker',
		jqueryLayout: 'libs/jquery.layout/jquery.layout-1.3.0',
		pagination: 'libs/jquery.pagination/js/pagination',
//		mapbox: 'libs/mapbox/mapbox',
		leaflet: 'libs/leaflet/leaflet',
//		mapbox: '//api.tiles.mapbox.com/mapbox.js/v1.4.0/mapbox',
		leafletDraw: 'libs/leaflet.draw/js/leaflet.draw',
		leafletFullscreen: 'libs/leaflet.fullscreen/js/leaflet.fullscreen',
		leafletExpandibleControl: 'libs/leaflet.expandible.control/js/leaflet.expandible.control',
		leafletButtonControl: 'libs/leaflet.button.control/js/leaflet.button.control',
		leafletLocationFilter: 'libs/leaflet.locationfilter/locationfilter',
		leafletMarkerCluster: 'libs/leaflet.markercluster/js/leaflet.markercluster',
		leafletGoogle: 'libs/leaflet.google/js/leaflet.google',
		leafletDvf: 'libs/leaflet.dvf/leaflet-dvf.min',
		leafletHeat: 'libs/leaflet.heat/leaflet-heatmap',
		heatMap: 'libs/leaflet.heat/heatmap.min',
		opensearchNavigator: 'libs/jquery.opensearchNavigator/js/opensearchNavigator',
		opensearchFormIt: 'libs/jquery.opensearchFormIt/js/opensearchFormIt',
		opensearchFormItGeoExtensions: 'libs/jquery.opensearchFormIt/extensions/geo',
		opensearchSlurper: 'libs/opensearchSlurper/js/opensearchSlurper',
		wpsSlurper: 'libs/wpsSlurper/js/wpsSlurper',
		moment: 'libs/moment/moment.min',
		underscorestring: 'libs/underscore/underscore.string.min',
		multiFieldExtender: 'libs/jquery.multiFieldExtender/js/jquery.multiFieldExtender-2.0.min',
		prettify: 'libs/prettify/js/prettify',
		vkbeautify: 'libs/vk.beautify/vkbeautify.0.99.00.beta',
	},
	shim: {
		underscore: {
			exports: '_'
		},
		can: {
			deps: ['jquery'],
			exports: 'can',
		},
		bootstrap: ['jquery'],
		bootbox: ['jquery', 'bootstrap'],
		loadmask: ['jquery'],
		jqueryLayout: ['jquery'],
		opensearchNavigator: [
			'jquery',
			'jqueryUI',
			'loadmask',
			'opensearchFormIt',
			'opensearchFormItGeoExtensions',
			'opensearchSlurper',
			'pagination',
			'leaflet',
			'jsonViewer',
			'jsonTable',
			'leafletDraw',
			'leafletExpandibleControl',
			'leafletButtonControl',
			//'leafletLocationFilter',
		],
		jqueryUI: ['jquery'],
		jqrange: ['jquery', 'jqueryUI'],
		jsonTable: ['jquery'],
		jsonViewer: ['jquery'],
		jqueryValidate: ['jquery'],
		pagination: ['jquery', 'jqueryUI'],
		opensearchFormIt: [
		                   'jquery',
		                   'loadmask',
		                   'opensearchSlurper',
		                   'jqueryValidate',
		                   'datePicker',
		                   ],
        opensearchFormItGeoExtensions: ['opensearchFormIt'],
        jqueryFullscreen: ['jquery'],
		leafletButtonControl: ['leaflet'],
		leafletDraw: ['leaflet'],
		leafletExpandibleControl: ['leaflet'],
		leafletMarkerCluster: ['leaflet'],
		leafletDvf: ['leaflet'],
		leafletLocationFilter: ['leaflet', 'leafletDraw', 'leafletButtonControl'],
		leafletGoogle: ['leaflet'],
		leafletHeat: ['leaflet'],
		leafletHeat: ['heatMap'],
		opensearchSlurper: ['jquery'],
		wpsSlurper: ['jquery', 'jqueryNamespace'],
		jqueryNamespace: ['jquery'],
		datePicker: ['jquery'],
		multiFieldExtender: ['jquery'],
		underscorestring: ['underscore'],
	}
});


// init
require(['geobrowser/app'], function(App){
	window.App = App;
	App.init();
});
